### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by breandan** [rusi/duckietown.dev.land#11]
After merging from [`duckietown/Software/master18`](https://github.com/duckietown/Software/tree/master18), we have the following issue when running `roslaunch pkg_name talker.launch` on an Ubuntu x86 machine: 

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 471, in load_config_default
    config.assign_machines()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 222, in assign_machines
    if [m for m in machine_unify_dict.values() if not is_machine_local(m)]:
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/core.py", line 97, in is_machine_local
    local_addresses = ['localhost'] + rosgraph.network.get_local_addresses()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 218, in get_local_addresses
    for iface in netifaces.interfaces():
OSError: [Errno 97] Address family not supported by protocol
```

**Comment by breandan** [comment]
Somehow, this is related to #17.

**Comment by breandan** [comment]
A ha! Thank you past @breandan for this helpful clue. I should have consulted you before going down this very long rabbit hole. This [issue](https://bugs.launchpad.net/qemu/+bug/1581695) is caused by an older version of `qemu-arm-static`. We never tested this code path on x86. The fix is to update qemu. Will deploy a fix shortly. @bhairavmehta95
