### ISSUE TITLE
ImportError: No module named geometry

### ISSUE THREAD

**Issue by breandan** [rusi/duckietown.dev.land#16]
Running `make build-machines` produces the following error on [`master18`](https://github.com/duckietown/Software/tree/master18):

```
rosrun duckieteam create-machines
Traceback (most recent call last):
  File "/home/software/catkin_ws/src/00-infrastructure/duckieteam/scripts/create-machines", line 2, in <module>
    from duckieteam.cli.create_machines import CreateMachines
  File "/home/software/catkin_ws/devel/lib/python2.7/dist-packages/duckieteam/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
  File "/home/software/catkin_ws/src/00-infrastructure/duckieteam/include/duckieteam/persons.py", line 2, in <module>
    import duckietown_utils as dtu 
  File "/home/software/catkin_ws/devel/lib/python2.7/dist-packages/duckietown_utils/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
ImportError: No module named geometry
Makefiles/Makefile.build.mk:24: recipe for target 'build-machines' failed
make: *** [build-machines] Error 1
```

**Comment by breandan** [comment]
Fixed. Was missing a some requirements from [`dependencies_common.sh`](https://github.com/duckietown/Software/blob/master/dependencies_common.sh) and `requirements.txt`. Ultimately, these files should no longer be necessary to run [duckietown/software](https://github.com/duckietown/software).
