### ISSUE TITLE
OSError: libbcm_host.so: No such file or directory

### ISSUE THREAD

**Issue by breandan** [rusi/duckietown.dev.land#26]
```
root@de2f91fa1371:/home/software# roslaunch duckietown line_detector.launch veh:=docker line_detector_param_file_name:=$* verbose:=false
... logging to /root/.ros/log/24811616-75a1-11e8-a243-0242ac110005/roslaunch-de2f91fa1371-1748.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:43135/

SUMMARY
========

CLEAR PARAMETERS
 * /docker/cam_info_reader_node/
 * /docker/camera_node/
 * /docker/line_detector_node/

PARAMETERS
 * /docker/cam_info_reader_node/cali_file_name: docker
 * /docker/cam_info_reader_node/config: baseline
 * /docker/cam_info_reader_node/image_type: compressed
 * /docker/cam_info_reader_node/pub_freq: 1.0
 * /docker/camera_node/framerate_high: 30
 * /docker/camera_node/framerate_low: 15
 * /docker/camera_node/res_h: 480
 * /docker/camera_node/res_w: 640
 * /docker/line_detector_node/detector: ['line_detector.L...
 * /docker/line_detector_node/img_size: [120, 160]
 * /docker/line_detector_node/top_cutoff: 40
 * /docker/line_detector_node/verbose: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /docker/
    cam_info_reader_node (pi_camera/cam_info_reader_node.py)
    camera_node (pi_camera/camera_node_sequence.py)
    line_detector_node (line_detector/line_detector_node.py)

auto-starting new master
process[master]: started with pid [1758]
ROS_MASTER_URI=http://localhost:11311/

setting /run_id to 24811616-75a1-11e8-a243-0242ac110005
process[rosout-1]: started with pid [1771]
started core service [/rosout]
process[docker/camera_node-2]: started with pid [1791]
process[docker/cam_info_reader_node-3]: started with pid [1792]
process[docker/line_detector_node-4]: started with pid [1793]
Traceback (most recent call last):
  File "/home/software/catkin_ws/src/05-teleop/pi_camera/src/camera_node_sequence.py", line 9, in <module>
    from picamera import PiCamera
  File "/usr/local/lib/python2.7/dist-packages/picamera/__init__.py", line 72, in <module>
    from picamera.exc import (
  File "/usr/local/lib/python2.7/dist-packages/picamera/exc.py", line 41, in <module>
    import picamera.mmal as mmal
  File "/usr/local/lib/python2.7/dist-packages/picamera/mmal.py", line 47, in <module>
    from .bcm_host import VCOS_UNSIGNED
  File "/usr/local/lib/python2.7/dist-packages/picamera/bcm_host.py", line 47, in <module>
    _lib = ct.CDLL('libbcm_host.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbcm_host.so: cannot open shared object file: No such file or directory
================================================================================REQUIRED process [docker/camera_node-2] has died!
process has died [pid 1791, exit code 1, cmd /home/software/catkin_ws/src/05-teleop/pi_camera/src/camera_node_sequence.py __name:=camera_node __log:=/root/.ros/log/24811616-75a1-11e8-a243-0242ac110005/docker-camera_node-2.log].
log file: /root/.ros/log/24811616-75a1-11e8-a243-0242ac110005/docker-camera_node-2*.log
Initiating shutdown!
================================================================================
[docker/line_detector_node-4] killing on exit
[docker/cam_info_reader_node-3] killing on exit
[docker/camera_node-2] killing on exit
Traceback (most recent call last):
  File "/home/software/catkin_ws/src/10-lane-control/line_detector/src/line_detector_node.py", line 7, in <module>
    from anti_instagram import AntiInstagram
  File "/home/software/catkin_ws/devel/lib/python2.7/dist-packages/anti_instagram/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 7, in <module>
  File "/home/software/catkin_ws/src/10-lane-control/anti_instagram/include/anti_instagram/anti_instagram_imp.py", line 6, in <module>
    import duckietown_utils as dtu
  File "/home/software/catkin_ws/devel/lib/python2.7/dist-packages/duckietown_utils/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/geometry/__init__.py", line 57, in <module>
    from .distances import *
  File "/usr/local/lib/python2.7/dist-packages/geometry/distances/__init__.py", line 3, in <module>
    from .spherical import *
  File "/usr/local/lib/python2.7/dist-packages/geometry/distances/spherical.py", line 6, in <module>
    new_contract('distances', 'array[NxN](>=0,<=pi)')
  File "/usr/local/lib/python2.7/dist-packages/contracts/__init__.py", line 28, in new_contract
    return new_contract_main(*args)
  File "/usr/local/lib/python2.7/dist-packages/contracts/main.py", line 547, in new_contract
    return new_contract_impl(*args)
  File "/usr/local/lib/python2.7/dist-packages/contracts/main.py", line 601, in new_contract_impl
    bare_contract = parse_contract_string(condition)
  File "/usr/local/lib/python2.7/dist-packages/contracts/main.py", line 660, in parse_contract_string
    return parse_contract_string_actual(string)
  File "/usr/local/lib/python2.7/dist-packages/contracts/main_actual.py", line 27, in parse_contract_string_actual
    parseAll=True)[0]
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3983, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3386, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3848, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3386, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/software/catkin_ws/src/05-teleop/pi_camera/src/cam_info_reader_node.py", line 67, in <module>
    rospy.init_node('cam_info_reader', anonymous=False)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 323, in init_node
    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")
rospy.exceptions.ROSInitException: init_node interrupted before it could complete
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by breandan** [comment]
This `libbcm_host.so` file is located on Hypriot, under `/opt/vc/lib`, but not inside the Docker container.

**Comment by breandan** [comment]
Obsolete. Closing.
