### ISSUE TITLE
Error: data_class [type] is not a message data class

### ISSUE THREAD

**Issue by breandan** [rusi/duckietown.dev.land#27]
Running `roslaunch duckietown_demos lane_following.launch line_detector_param_file_name:=$*` produces the following error:

```
root@de2f91fa1371:/home/software# roslaunch duckietown_demos lane_following.launch line_detector_param_file_name:=$*
... logging to /root/.ros/log/d9d33f16-75a2-11e8-9ee4-0242ac110005/roslaunch-de2f91fa1371-2071.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:37485/

SUMMARY
========

CLEAR PARAMETERS
 * /docker/cam_info_reader_node/
 * /docker/camera_node/
 * /docker/fake_coordinator_node/
 * /docker/fsm_node/
 * /docker/ground_projection/
 * /docker/inverse_kinematics_node/
 * /docker/joy_mapper_node/
 * /docker/joy_node/
 * /docker/lane_controller_node/
 * /docker/lane_filter_node/
 * /docker/lane_pose_visualizer_node/
 * /docker/led_emitter_node/
 * /docker/line_detector_node/
 * /docker/logic_gate_node/
 * /docker/wheels_driver_node/

PARAMETERS
 * /docker/cam_info_reader_node/cali_file_name: docker
 * /docker/cam_info_reader_node/config: baseline
 * /docker/cam_info_reader_node/image_type: compressed
 * /docker/cam_info_reader_node/pub_freq: 1.0
 * /docker/camera_node/framerate_high: 30
 * /docker/camera_node/framerate_low: 15
 * /docker/camera_node/res_h: 480
 * /docker/camera_node/res_w: 640
 * /docker/car_cmd_switch_node/mappings/ARRIVE_AT_STOP_LINE: stop
 * /docker/car_cmd_switch_node/mappings/AVOID_OBSTACLE: obstacle
 * /docker/car_cmd_switch_node/mappings/AVOID_VEHICLE: vehicle
 * /docker/car_cmd_switch_node/mappings/DEEP_LANE_FOLLOWING: deep_learning
 * /docker/car_cmd_switch_node/mappings/INTERSECTION_CONTROL: intersection
 * /docker/car_cmd_switch_node/mappings/INTERSECTION_COORDINATION: stop
 * /docker/car_cmd_switch_node/mappings/INTERSECTION_RECOVERY: recovery
 * /docker/car_cmd_switch_node/mappings/LANE_FOLLOWING: lane
 * /docker/car_cmd_switch_node/mappings/LANE_FOLLOWING_AVOID: lane
 * /docker/car_cmd_switch_node/mappings/LANE_RECOVERY: recovery
 * /docker/car_cmd_switch_node/mappings/LOCALIZATION: stop
 * /docker/car_cmd_switch_node/mappings/NORMAL_JOYSTICK_CONTROL: joystick
 * /docker/car_cmd_switch_node/mappings/PARALLEL_AUTONOMY: parallel_autonomy
 * /docker/car_cmd_switch_node/mappings/PARKING: parking
 * /docker/car_cmd_switch_node/mappings/SAFE_JOYSTICK_CONTROL: joystick
 * /docker/car_cmd_switch_node/mode_topic: fsm_node/mode
 * /docker/car_cmd_switch_node/source_topics/deep_learning: duckiebot_il_lane...
 * /docker/car_cmd_switch_node/source_topics/intersection: open_loop_interse...
 * /docker/car_cmd_switch_node/source_topics/joystick: joy_mapper_node/c...
 * /docker/car_cmd_switch_node/source_topics/lane: lane_controller_n...
 * /docker/car_cmd_switch_node/source_topics/obstacle: simple_stop_contr...
 * /docker/car_cmd_switch_node/source_topics/parallel_autonomy: lane_supervisor_n...
 * /docker/car_cmd_switch_node/source_topics/parking: lane_controller_n...
 * /docker/car_cmd_switch_node/source_topics/recovery: lane_recovery_nod...
 * /docker/car_cmd_switch_node/source_topics/stop: simple_stop_contr...
 * /docker/car_cmd_switch_node/source_topics/vehicle: vehicle_avoidance...
 * /docker/duckiebot_visualizer/veh_name: docker
 * /docker/fsm_node/events/apriltag_intersection/msg_type: BoolStamped
 * /docker/fsm_node/events/apriltag_intersection/topic: apriltags_postpro...
 * /docker/fsm_node/events/apriltag_intersection/trigger: True
 * /docker/fsm_node/events/apriltag_parking_and_parking_active/msg_type: BoolStamped
 * /docker/fsm_node/events/apriltag_parking_and_parking_active/topic: logic_gate_node/a...
 * /docker/fsm_node/events/apriltag_parking_and_parking_active/trigger: True
 * /docker/fsm_node/events/at_stop_line/msg_type: BoolStamped
 * /docker/fsm_node/events/at_stop_line/topic: stop_line_filter_...
 * /docker/fsm_node/events/at_stop_line/trigger: True
 * /docker/fsm_node/events/at_stop_line_and_parking_off/msg_type: BoolStamped
 * /docker/fsm_node/events/at_stop_line_and_parking_off/topic: logic_gate_node/a...
 * /docker/fsm_node/events/at_stop_line_and_parking_off/trigger: True
 * /docker/fsm_node/events/at_stop_line_and_parking_on/msg_type: BoolStamped
 * /docker/fsm_node/events/at_stop_line_and_parking_on/topic: logic_gate_node/a...
 * /docker/fsm_node/events/at_stop_line_and_parking_on/trigger: True
 * /docker/fsm_node/events/deep_lane_following_off/msg_type: BoolStamped
 * /docker/fsm_node/events/deep_lane_following_off/topic: joy_mapper_node/d...
 * /docker/fsm_node/events/deep_lane_following_off/trigger: False
 * /docker/fsm_node/events/deep_lane_following_on/msg_type: BoolStamped
 * /docker/fsm_node/events/deep_lane_following_on/topic: joy_mapper_node/d...
 * /docker/fsm_node/events/deep_lane_following_on/trigger: True
 * /docker/fsm_node/events/intersection_done_and_deep_lane_off/msg_type: BoolStamped
 * /docker/fsm_node/events/intersection_done_and_deep_lane_off/topic: logic_gate_node/i...
 * /docker/fsm_node/events/intersection_done_and_deep_lane_off/trigger: True
 * /docker/fsm_node/events/intersection_done_and_deep_lane_on/msg_type: BoolStamped
 * /docker/fsm_node/events/intersection_done_and_deep_lane_on/topic: logic_gate_node/i...
 * /docker/fsm_node/events/intersection_done_and_deep_lane_on/trigger: True
 * /docker/fsm_node/events/intersection_go/msg_type: BoolStamped
 * /docker/fsm_node/events/intersection_go/topic: logic_gate_node/i...
 * /docker/fsm_node/events/intersection_go/trigger: True
 * /docker/fsm_node/events/joystick_override_off_and_deep_lane_off/msg_type: BoolStamped
 * /docker/fsm_node/events/joystick_override_off_and_deep_lane_off/topic: logic_gate_node/j...
 * /docker/fsm_node/events/joystick_override_off_and_deep_lane_off/trigger: True
 * /docker/fsm_node/events/joystick_override_off_and_deep_lane_on/msg_type: BoolStamped
 * /docker/fsm_node/events/joystick_override_off_and_deep_lane_on/topic: logic_gate_node/j...
 * /docker/fsm_node/events/joystick_override_off_and_deep_lane_on/trigger: True
 * /docker/fsm_node/events/joystick_override_on_and_parallel_autonomy_off/msg_type: BoolStamped
 * /docker/fsm_node/events/joystick_override_on_and_parallel_autonomy_off/topic: logic_gate_node/j...
 * /docker/fsm_node/events/joystick_override_on_and_parallel_autonomy_off/trigger: True
 * /docker/fsm_node/events/joystick_override_on_and_parallel_autonomy_on/msg_type: BoolStamped
 * /docker/fsm_node/events/joystick_override_on_and_parallel_autonomy_on/topic: logic_gate_node/j...
 * /docker/fsm_node/events/joystick_override_on_and_parallel_autonomy_on/trigger: True
 * /docker/fsm_node/events/parallel_autonomy_off/msg_type: BoolStamped
 * /docker/fsm_node/events/parallel_autonomy_off/topic: joy_mapper_node/p...
 * /docker/fsm_node/events/parallel_autonomy_off/trigger: False
 * /docker/fsm_node/events/parallel_autonomy_on/msg_type: BoolStamped
 * /docker/fsm_node/events/parallel_autonomy_on/topic: joy_mapper_node/p...
 * /docker/fsm_node/events/parallel_autonomy_on/trigger: True
 * /docker/fsm_node/events/start_avoidance/msg_type: BoolStamped
 * /docker/fsm_node/events/start_avoidance/topic: joy_mapper_node/s...
 * /docker/fsm_node/events/start_avoidance/trigger: True
 * /docker/fsm_node/global_transitions/joystick_override_on_and_parallel_autonomy_off: NORMAL_JOYSTICK_C...
 * /docker/fsm_node/global_transitions/joystick_override_on_and_parallel_autonomy_on: SAFE_JOYSTICK_CON...
 * /docker/fsm_node/initial_state: NORMAL_JOYSTICK_C...
 * /docker/fsm_node/nodes/LED_coordination_node: LED_coordination_...
 * /docker/fsm_node/nodes/LED_detection_node: LED_detection_nod...
 * /docker/fsm_node/nodes/apriltag_node: apriltag_detector...
 * /docker/fsm_node/nodes/central_fleet_planning_node: central_fleet_pla...
 * /docker/fsm_node/nodes/decoder_node: decoder_node/switch
 * /docker/fsm_node/nodes/duckiebot_il_lane_following: duckiebot_il_lane...
 * /docker/fsm_node/nodes/framerate_high: camera_node/frame...
 * /docker/fsm_node/nodes/implicit_coordination_node: implicit_coordina...
 * /docker/fsm_node/nodes/intersection_localization_node: intersection_loca...
 * /docker/fsm_node/nodes/intersection_navigation_node: intersection_navi...
 * /docker/fsm_node/nodes/lane_controller_node: lane_controller_n...
 * /docker/fsm_node/nodes/lane_filter_node: lane_filter_node/...
 * /docker/fsm_node/nodes/led_detector_node: LED_detector_node...
 * /docker/fsm_node/nodes/led_emitter_node: led_emitter_node/...
 * /docker/fsm_node/nodes/line_detector_node: line_detector_nod...
 * /docker/fsm_node/nodes/obstacle_avoidance_node: obstacle_avoidanc...
 * /docker/fsm_node/nodes/parking_control: parking_control/s...
 * /docker/fsm_node/nodes/parking_path_planning: parking_path_plan...
 * /docker/fsm_node/nodes/parking_perception_localization: parking_perceptio...
 * /docker/fsm_node/nodes/static_object_detector_node: static_object_det...
 * /docker/fsm_node/nodes/stop_line_filter_node: stop_line_filter_...
 * /docker/fsm_node/nodes/vehicle_avoidance_control_node: vehicle_avoidance...
 * /docker/fsm_node/nodes/vehicle_detection_node: vehicle_detection...
 * /docker/fsm_node/nodes/vehicle_filter_node: vehicle_filter_no...
 * /docker/fsm_node/states/ARRIVE_AT_STOP_LINE/active_nodes: ['apriltag_node',...
 * /docker/fsm_node/states/ARRIVE_AT_STOP_LINE/current_status: implemented
 * /docker/fsm_node/states/ARRIVE_AT_STOP_LINE/transitions/apriltag_intersection: INTERSECTION_COOR...
 * /docker/fsm_node/states/ARRIVE_AT_STOP_LINE/transitions/apriltag_parking_and_parking_active: PARKING
 * /docker/fsm_node/states/DEEP_LANE_FOLLOWING/active_nodes: ['decoder_node', ...
 * /docker/fsm_node/states/DEEP_LANE_FOLLOWING/transitions/at_stop_line_and_parking_off: INTERSECTION_COOR...
 * /docker/fsm_node/states/DEEP_LANE_FOLLOWING/transitions/at_stop_line_and_parking_on: ARRIVE_AT_STOP_LINE
 * /docker/fsm_node/states/DEEP_LANE_FOLLOWING/transitions/deep_lane_following_off: LANE_FOLLOWING
 * /docker/fsm_node/states/INTERSECTION_CONTROL/active_nodes: ['apriltag_node',...
 * /docker/fsm_node/states/INTERSECTION_CONTROL/current_status: in_progress
 * /docker/fsm_node/states/INTERSECTION_CONTROL/transitions/intersection_done_and_deep_lane_off: LANE_FOLLOWING
 * /docker/fsm_node/states/INTERSECTION_CONTROL/transitions/intersection_done_and_deep_lane_on: DEEP_LANE_FOLLOWING
 * /docker/fsm_node/states/INTERSECTION_COORDINATION/active_nodes: ['decoder_node', ...
 * /docker/fsm_node/states/INTERSECTION_COORDINATION/current_status: in_progress
 * /docker/fsm_node/states/INTERSECTION_COORDINATION/lights: ['coordination']
 * /docker/fsm_node/states/INTERSECTION_COORDINATION/transitions/intersection_go: INTERSECTION_CONTROL
 * /docker/fsm_node/states/LANE_FOLLOWING/active_nodes: ['decoder_node', ...
 * /docker/fsm_node/states/LANE_FOLLOWING/current_status: in_progress
 * /docker/fsm_node/states/LANE_FOLLOWING/lights: ['lane_following']
 * /docker/fsm_node/states/LANE_FOLLOWING/transitions/at_stop_line_and_parking_off: INTERSECTION_COOR...
 * /docker/fsm_node/states/LANE_FOLLOWING/transitions/at_stop_line_and_parking_on: ARRIVE_AT_STOP_LINE
 * /docker/fsm_node/states/LANE_FOLLOWING/transitions/deep_lane_following_on: DEEP_LANE_FOLLOWING
 * /docker/fsm_node/states/NORMAL_JOYSTICK_CONTROL/active_nodes: ['lane_filter_nod...
 * /docker/fsm_node/states/NORMAL_JOYSTICK_CONTROL/current_status: implemented
 * /docker/fsm_node/states/NORMAL_JOYSTICK_CONTROL/lights: ['joystick']
 * /docker/fsm_node/states/NORMAL_JOYSTICK_CONTROL/transitions/joystick_override_off_and_deep_lane_off: LANE_FOLLOWING
 * /docker/fsm_node/states/NORMAL_JOYSTICK_CONTROL/transitions/joystick_override_off_and_deep_lane_on: DEEP_LANE_FOLLOWING
 * /docker/fsm_node/states/NORMAL_JOYSTICK_CONTROL/transitions/parallel_autonomy_on: SAFE_JOYSTICK_CON...
 * /docker/fsm_node/states/PARKING/active_nodes: ['decoder_node', ...
 * /docker/fsm_node/states/PARKING/current_status: in_progress
 * /docker/fsm_node/states/PARKING/transitions/at_stop_line_and_parking_off: INTERSECTION_COOR...
 * /docker/fsm_node/states/PARKING/transitions/at_stop_line_and_parking_on: ARRIVE_AT_STOP_LINE
 * /docker/fsm_node/states/SAFE_JOYSTICK_CONTROL/active_nodes: ['decoder_node', ...
 * /docker/fsm_node/states/SAFE_JOYSTICK_CONTROL/current_status: implemented
 * /docker/fsm_node/states/SAFE_JOYSTICK_CONTROL/lights: ['joystick']
 * /docker/fsm_node/states/SAFE_JOYSTICK_CONTROL/transitions/joystick_override_off_and_deep_lane_off: LANE_FOLLOWING
 * /docker/fsm_node/states/SAFE_JOYSTICK_CONTROL/transitions/joystick_override_off_and_deep_lane_on: DEEP_LANE_FOLLOWING
 * /docker/fsm_node/states/SAFE_JOYSTICK_CONTROL/transitions/parallel_autonomy_off: NORMAL_JOYSTICK_C...
 * /docker/ground_projection/config: baseline
 * /docker/ground_projection/config_file_name: docker
 * /docker/joy_mapper_node/bicycle_kinematics: 0.0
 * /docker/joy_mapper_node/simulated_vehicle_length: 0.18
 * /docker/joy_mapper_node/speed_gain: 0.41
 * /docker/joy_mapper_node/steer_angle_gain: 1.04
 * /docker/joy_mapper_node/steer_gain: 8.3
 * /docker/joy_node/autorepeat_rate: 2.0
 * /docker/joy_node/coalesce_interval: 0.02
 * /docker/joy_node/deadzone: 0.01
 * /docker/joy_node/dev: /dev/input/js0
 * /docker/lane_controller_node/d_offset: 0.0
 * /docker/lane_controller_node/d_thres: 0.2615
 * /docker/lane_controller_node/k_Id: 2.5
 * /docker/lane_controller_node/k_Iphi: 0.0
 * /docker/lane_controller_node/k_d: -60
 * /docker/lane_controller_node/k_theta: -10
 * /docker/lane_controller_node/theta_thres: 0.523
 * /docker/lane_controller_node/v_bar: 0.3864
 * /docker/lane_filter_node/filter: ['lane_filter.Lan...
 * /docker/lane_filter_node/use_propagation: True
 * /docker/led_emitter_node/LED_protocol/colors/black: [0, 0, 0]
 * /docker/led_emitter_node/LED_protocol/colors/blue: [0, 0, 1]
 * /docker/led_emitter_node/LED_protocol/colors/cyan: [0, 1, 1]
 * /docker/led_emitter_node/LED_protocol/colors/green: [0, 1, 0]
 * /docker/led_emitter_node/LED_protocol/colors/purple: [1, 0, 1]
 * /docker/led_emitter_node/LED_protocol/colors/red: [1, 0, 0]
 * /docker/led_emitter_node/LED_protocol/colors/white: [0, 0, 0]
 * /docker/led_emitter_node/LED_protocol/colors/yellow: [1, 1, 0]
 * /docker/led_emitter_node/LED_protocol/frequencies/f1: 7.8
 * /docker/led_emitter_node/LED_protocol/frequencies/f2: 4
 * /docker/led_emitter_node/LED_protocol/frequencies/f3: 5.7
 * /docker/led_emitter_node/LED_protocol/signals/CAR_SIGNAL_A/color: green
 * /docker/led_emitter_node/LED_protocol/signals/CAR_SIGNAL_A/frequency: 7.8
 * /docker/led_emitter_node/LED_protocol/signals/CAR_SIGNAL_B/color: purple
 * /docker/led_emitter_node/LED_protocol/signals/CAR_SIGNAL_B/frequency: 4
 * /docker/led_emitter_node/LED_protocol/signals/CAR_SIGNAL_C/color: yellow
 * /docker/led_emitter_node/LED_protocol/signals/CAR_SIGNAL_C/frequency: 5.7
 * /docker/led_emitter_node/LED_protocol/signals/light_off/color: black
 * /docker/led_emitter_node/LED_protocol/signals/light_off/frequency: 7.8
 * /docker/led_emitter_node/LED_protocol/signals/traffic_light_go/color: green
 * /docker/led_emitter_node/LED_protocol/signals/traffic_light_go/frequency: 7.8
 * /docker/led_emitter_node/LED_protocol/signals/traffic_light_stop/color: red
 * /docker/led_emitter_node/LED_protocol/signals/traffic_light_stop/frequency: 5.7
 * /docker/line_detector_node/detector: ['line_detector.L...
 * /docker/line_detector_node/img_size: [120, 160]
 * /docker/line_detector_node/top_cutoff: 40
 * /docker/line_detector_node/verbose: False
 * /docker/logic_gate_node/events/apriltag_parking/msg_type: BoolStamped
 * /docker/logic_gate_node/events/apriltag_parking/topic: apriltags_postpro...
 * /docker/logic_gate_node/events/apriltag_parking/trigger: True
 * /docker/logic_gate_node/events/at_stop_line/msg_type: BoolStamped
 * /docker/logic_gate_node/events/at_stop_line/topic: stop_line_filter_...
 * /docker/logic_gate_node/events/at_stop_line/trigger: True
 * /docker/logic_gate_node/events/deep_lane_following_off/default: True
 * /docker/logic_gate_node/events/deep_lane_following_off/msg_type: BoolStamped
 * /docker/logic_gate_node/events/deep_lane_following_off/topic: joy_mapper_node/d...
 * /docker/logic_gate_node/events/deep_lane_following_off/trigger: False
 * /docker/logic_gate_node/events/deep_lane_following_on/default: False
 * /docker/logic_gate_node/events/deep_lane_following_on/msg_type: BoolStamped
 * /docker/logic_gate_node/events/deep_lane_following_on/topic: joy_mapper_node/d...
 * /docker/logic_gate_node/events/deep_lane_following_on/trigger: True
 * /docker/logic_gate_node/events/intersection_done/msg_type: BoolStamped
 * /docker/logic_gate_node/events/intersection_done/topic: intersection_navi...
 * /docker/logic_gate_node/events/intersection_done/trigger: True
 * /docker/logic_gate_node/events/intersection_go_explicit/msg_type: BoolStamped
 * /docker/logic_gate_node/events/intersection_go_explicit/topic: LED_coordination/...
 * /docker/logic_gate_node/events/intersection_go_explicit/trigger: True
 * /docker/logic_gate_node/events/intersection_go_implicit/msg_type: BoolStamped
 * /docker/logic_gate_node/events/intersection_go_implicit/topic: implicit_coord/fl...
 * /docker/logic_gate_node/events/intersection_go_implicit/trigger: True
 * /docker/logic_gate_node/events/joystick_override_off/msg_type: BoolStamped
 * /docker/logic_gate_node/events/joystick_override_off/topic: joy_mapper_node/j...
 * /docker/logic_gate_node/events/joystick_override_off/trigger: False
 * /docker/logic_gate_node/events/joystick_override_on/msg_type: BoolStamped
 * /docker/logic_gate_node/events/joystick_override_on/topic: joy_mapper_node/j...
 * /docker/logic_gate_node/events/joystick_override_on/trigger: True
 * /docker/logic_gate_node/events/parallel_autonomy_off/default: True
 * /docker/logic_gate_node/events/parallel_autonomy_off/msg_type: BoolStamped
 * /docker/logic_gate_node/events/parallel_autonomy_off/topic: joy_mapper_node/p...
 * /docker/logic_gate_node/events/parallel_autonomy_off/trigger: False
 * /docker/logic_gate_node/events/parallel_autonomy_on/default: False
 * /docker/logic_gate_node/events/parallel_autonomy_on/msg_type: BoolStamped
 * /docker/logic_gate_node/events/parallel_autonomy_on/topic: joy_mapper_node/p...
 * /docker/logic_gate_node/events/parallel_autonomy_on/trigger: True
 * /docker/logic_gate_node/events/parking_off/default: True
 * /docker/logic_gate_node/events/parking_off/msg_type: BoolStamped
 * /docker/logic_gate_node/events/parking_off/topic: parking_on
 * /docker/logic_gate_node/events/parking_off/trigger: False
 * /docker/logic_gate_node/events/parking_on/default: False
 * /docker/logic_gate_node/events/parking_on/msg_type: BoolStamped
 * /docker/logic_gate_node/events/parking_on/topic: parking_on
 * /docker/logic_gate_node/events/parking_on/trigger: True
 * /docker/logic_gate_node/gates/at_stop_line_and_parking_off/gate_type: AND
 * /docker/logic_gate_node/gates/at_stop_line_and_parking_off/inputs: ['at_stop_line', ...
 * /docker/logic_gate_node/gates/at_stop_line_and_parking_off/output_topic: ~at_stop_line_and...
 * /docker/logic_gate_node/gates/at_stop_line_and_parking_on/gate_type: AND
 * /docker/logic_gate_node/gates/at_stop_line_and_parking_on/inputs: ['at_stop_line', ...
 * /docker/logic_gate_node/gates/at_stop_line_and_parking_on/output_topic: ~at_stop_line_and...
 * /docker/logic_gate_node/gates/intersection_done_and_deep_lane_off/gate_type: AND
 * /docker/logic_gate_node/gates/intersection_done_and_deep_lane_off/inputs: ['intersection_do...
 * /docker/logic_gate_node/gates/intersection_done_and_deep_lane_off/output_topic: ~intersection_don...
 * /docker/logic_gate_node/gates/intersection_done_and_deep_lane_on/gate_type: AND
 * /docker/logic_gate_node/gates/intersection_done_and_deep_lane_on/inputs: ['intersection_do...
 * /docker/logic_gate_node/gates/intersection_done_and_deep_lane_on/output_topic: ~intersection_don...
 * /docker/logic_gate_node/gates/intersection_go/gate_type: OR
 * /docker/logic_gate_node/gates/intersection_go/inputs: ['intersection_go...
 * /docker/logic_gate_node/gates/intersection_go/output_topic: ~intersection_go
 * /docker/logic_gate_node/gates/joystick_override_off_and_deep_lane_off/gate_type: AND
 * /docker/logic_gate_node/gates/joystick_override_off_and_deep_lane_off/inputs: ['joystick_overri...
 * /docker/logic_gate_node/gates/joystick_override_off_and_deep_lane_off/output_topic: ~joystick_overrid...
 * /docker/logic_gate_node/gates/joystick_override_off_and_deep_lane_on/gate_type: AND
 * /docker/logic_gate_node/gates/joystick_override_off_and_deep_lane_on/inputs: ['joystick_overri...
 * /docker/logic_gate_node/gates/joystick_override_off_and_deep_lane_on/output_topic: ~joystick_overrid...
 * /docker/logic_gate_node/gates/joystick_override_on_and_parallel_autonomy_off/gate_type: AND
 * /docker/logic_gate_node/gates/joystick_override_on_and_parallel_autonomy_off/inputs: ['joystick_overri...
 * /docker/logic_gate_node/gates/joystick_override_on_and_parallel_autonomy_off/output_topic: ~joystick_overrid...
 * /docker/logic_gate_node/gates/joystick_override_on_and_parallel_autonomy_on/gate_type: AND
 * /docker/logic_gate_node/gates/joystick_override_on_and_parallel_autonomy_on/inputs: ['joystick_overri...
 * /docker/logic_gate_node/gates/joystick_override_on_and_parallel_autonomy_on/output_topic: ~joystick_overrid...
 * /docker/wheels_driver_node/min_rad: 0.06
 * /docker/wheels_driver_node/use_rad_lim: False
 * /docker/wheels_driver_node/wheel_distance: 0.103
 * /enable_statistics: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /docker/
    anti_instagram_node (anti_instagram/anti_instagram_node.py)
    cam_info_reader_node (pi_camera/cam_info_reader_node.py)
    camera_node (pi_camera/camera_node_sequence.py)
    car_cmd_switch_node (dagu_car/car_cmd_switch_node.py)
    duckiebot_visualizer (duckiebot_visualizer/duckiebot_visualizer.py)
    fake_coordinator_node (veh_coordinator/fake_coordinator_node.py)
    fsm_node (fsm/fsm_node.py)
    ground_projection (ground_projection/ground_projection_node.py)
    inverse_kinematics_node (dagu_car/inverse_kinematics_node.py)
    joy_mapper_node (joy_mapper/joy_mapper_node.py)
    joy_node (joy/joy_node)
    lane_controller_node (lane_control/lane_controller_node.py)
    lane_filter_node (lane_filter/lane_filter_node.py)
    lane_pose_visualizer_node (lane_filter/lane_pose_visualizer_node.py)
    led_emitter_node (led_emitter/led_emitter_node.py)
    line_detector_node (line_detector/line_detector_node.py)
    logic_gate_node (fsm/logic_gate_node.py)
    wheels_driver_node (dagu_car/wheels_driver_node.py)
  /
    docker_to_map (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [2081]
ROS_MASTER_URI=http://localhost:11311/

setting /run_id to d9d33f16-75a2-11e8-9ee4-0242ac110005
process[rosout-1]: started with pid [2094]
started core service [/rosout]
process[docker/camera_node-2]: started with pid [2126]
process[docker/cam_info_reader_node-3]: started with pid [2127]
process[docker/inverse_kinematics_node-4]: started with pid [2128]
process[docker/wheels_driver_node-5]: started with pid [2129]
process[docker/joy_node-6]: started with pid [2130]
process[docker/joy_mapper_node-7]: started with pid [2133]
[ INFO] [1529620301.406483563]: Opened joystick: /dev/input/js0. deadzone_: 0.010000.
process[docker/fsm_node-8]: started with pid [2157]
process[docker/car_cmd_switch_node-9]: started with pid [2158]
[INFO] [1529620302.800537]: [/docker/wheels_driver_node] Initializing 
[INFO] [1529620302.851560]: [/docker/wheels_driver_node] ~use_rad_lim = False 
[INFO] [1529620302.890604]: [/docker/wheels_driver_node] ~min_rad = 0.06 
[INFO] [1529620302.931532]: [/docker/wheels_driver_node] ~wheel_distance = 0.103 
process[docker/logic_gate_node-10]: started with pid [2163]
[INFO] [1529620303.897709]: [/docker/joy_mapper_node] Initializing 
[INFO] [1529620303.932232]: [/docker/joy_mapper_node] ~speed_gain = 0.41 
[INFO] [1529620303.998170]: [/docker/joy_mapper_node] ~steer_gain = 8.3 
[INFO] [1529620304.050918]: [/docker/joy_mapper_node] ~bicycle_kinematics = 0.0 
[INFO] [1529620304.128163]: [/docker/joy_mapper_node] ~steer_angle_gain = 1.04 
[INFO] [1529620304.216030]: [/docker/joy_mapper_node] ~simulated_vehicle_length = 0.18 
process[docker/line_detector_node-11]: started with pid [2187]
process[docker/ground_projection-12]: started with pid [2225]
[INFO] [1529620305.878264]: [/docker/fsm_node] Initialized.
[INFO] [1529620305.884221]: [/docker/fsm_node] FSMState: NORMAL_JOYSTICK_CONTROL
[INFO] [1529620305.888184]: [/docker/car_cmd_switch_node] Car cmd switched to joystick in state NORMAL_JOYSTICK_CONTROL.
[INFO] [1529620305.970212]: [/docker/car_cmd_switch_node] Initialized. 
process[docker/duckiebot_visualizer-13]: started with pid [2306]
process[docker_to_map-14]: started with pid [2362]
process[docker/lane_filter_node-15]: started with pid [2442]
process[docker/lane_controller_node-16]: started with pid [2475]
[INFO] [1529620309.215672]: [/docker/duckiebot_visualizer] Initialzing.
[INFO] [1529620309.306236]: [/docker/duckiebot_visualizer] ~veh_name = docker 
[INFO] [1529620309.390580]: [/docker/duckiebot_visualizer] Initialzed.
process[docker/lane_pose_visualizer_node-17]: started with pid [2490]
process[docker/led_emitter_node-18]: started with pid [2500]
process[docker/fake_coordinator_node-19]: started with pid [2509]
Traceback (most recent call last):
  File "/home/software/catkin_ws/src/10-lane-control/lane_control/scripts/lane_controller_node.py", line 398, in <module>
    lane_control_node = lane_controller()
  File "/home/software/catkin_ws/src/10-lane-control/lane_control/scripts/lane_controller_node.py", line 39, in __init__
    self.subscriber = rospy.Subscriber(self.sub_topic, bool, self.obstacleFlagCallback)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 563, in __init__
    super(Subscriber, self).__init__(name, data_class, Registration.SUB)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 144, in __init__
    raise ValueError("data_class [%s] is not a message data class"%data_class.__class__.__name__)
ValueError: data_class [type] is not a message data class
process[docker/anti_instagram_node-20]: started with pid [2521]
================================================================================REQUIRED process [docker/lane_controller_node-16] has died!
process has died [pid 2475, exit code 1, cmd /home/software/catkin_ws/src/10-lane-control/lane_control/scripts/lane_controller_node.py lane_controller_node/lane_pose:=lane_filter_node/lane_pose lane_controller_node/lane_pose_intersection_navigation:=intersection_navigation_node/lane_pose_intersection_navigation fsm_node/mode:=fsm_node/lane_pose_intersection_navigation lane_controller_node/wheels_cmd_executed:=wheels_driver_node/wheels_cmd_executed lane_controller_node/actuator_params:=inverse_kinematics_node/actuator_params __name:=lane_controller_node __log:=/root/.ros/log/d9d33f16-75a2-11e8-9ee4-0242ac110005/docker-lane_controller_node-16.log].
log file: /root/.ros/log/d9d33f16-75a2-11e8-9ee4-0242ac110005/docker-lane_controller_node-16*.log
Initiating shutdown!
================================================================================
[docker/anti_instagram_node-20] killing on exit
[docker/fake_coordinator_node-19] killing on exit
Traceback (most recent call last):
  File "/home/software/catkin_ws/src/70-convenience-packages/veh_coordinator/src/fake_coordinator_node.py", line 2, in <module>
    import rospy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
[docker/led_emitter_node-18] killing on exit
    from .client import spin, myargv, init_node, \
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/__init__.py", line 54, in <module>
    import roslib.stacks
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/stacks.py", line 46, in <module>
[docker/lane_pose_visualizer_node-17] killing on exit
    import roslib.packages
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/packages.py", line 49, in <module>
    from catkin.find_in_workspaces import find_in_workspaces as catkin_find
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 36, in <module>
    from catkin_pkg.packages import find_packages
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 40, in <module>
    from .package import _get_package_xml
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 46, in <module>
    from catkin_pkg.condition import evaluate_condition
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/condition.py", line 17, in <module>
    import pyparsing
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3108, in <module>
[docker/lane_controller_node-16] killing on exit
Traceback (most recent call last):
...
```

**Comment by breandan** [comment]
Blocking #21.

**Comment by breandan** [comment]
Obsolete. Closing.
